# create new directories and files 
dir.create("scripts")
file.create("scripts/00-setup.R")
file.create("scripts/01-query.R")
file.create("scripts/02-tidy.R")
file.create("scripts/03-transform.R")
file.create("README.md")
dir.create("reports")
dir.create("figures")
dir.create("data-raw")
dir.create("data-tidy")
dir.create("data-viz")
